[package]
name = "sentineld"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.35.1"
tokio = { version = "1", features = ["full"] }
axum = "0.8.4"
prometheus = "0.14"
lazy_static = "1.5.0"
